Applied the patch provided by Jim Rudnicki, thanks Jim! It looks like it fixes the problem I had reported earlier with the following exception being throw sometimes:
The patch makes sure that the response and request get
recycled if finish() throws an Exception.

Internal Servlet Error:

java.lang.IllegalStateException: OutputStream is already being used for this request