Catch this exception and make people start over again...
  java.lang.reflect.InvocationTargetException:
org.tigris.scarab.util.ScarabException: A new transaction was set and a
transaction was already in progress.
    at
org.tigris.scarab.om.AttributeValue.startTransaction(AttributeValue.java:242)
    at
org.tigris.scarab.actions.ReportIssue.doEnterissue(ReportIssue.java:298)
    at java.lang.reflect.Method.invoke(Native Method)
    at
org.apache.turbine.modules.actions.TemplateAction.executeEvents(TemplateAction.java:171)
    at
org.apache.turbine.modules.actions.TemplateAction.perform(TemplateAction.java:115)