Change metadata to use Strings instead of Classes. Prevents icky ClassNotFoundExceptions and NoClassDefFoundErrors. Added convenience methods that take Classes and convert them to Strings.