catch exception when trying to create a SearchIndex because a common mistake is to make WEB-INF/index without permissions to write to it
jason/pier/dlr got hit by this on nagoya.

now, a nice exception is thrown and logged...

  java.lang.reflect.InvocationTargetException:
  java.lang.InstantiationException: Could not create new
  instance of SearchIndex. Could be a result of insufficient
  permission to write the Index to the disk. The default is
  towrite the Index into the WEB-INF/index directory.
	at org.tigris.scarab.util.word.SearchFactory.getInstance(SearchFactory.java:105)
	at org.tigris.scarab.util.word.IssueSearch.addTextMatches(IssueSearch.java:1012)

-jon